// swift-tools-version:5.9
// Generated by SAPIENT's release workflow for v0.6.0 — do not edit by hand.
// Source + docs: https://github.com/SkidGod4444/sapient (docs/MOBILE.md)
import PackageDescription

let package = Package(
    name: "Sapient",
    platforms: [.iOS(.v14), .macOS(.v12)],
    products: [
        .library(name: "Sapient", targets: ["Sapient"])
    ],
    targets: [
        .binaryTarget(
            name: "SapientFFI",
            url: "https://github.com/SkidGod4444/sapient/releases/download/v0.6.0/SapientFFI.xcframework.zip",
            checksum: "0e891834e773c5cc68c6de8a37f5490185a6276a3079e5716fed816156e875e6"),
        .target(
            name: "Sapient",
            dependencies: ["SapientFFI"],
            path: "Sources/Sapient",
            linkerSettings: [
                // The Rust staticlib carries C++ (esaxx) and iconv users.
                .linkedLibrary("c++"),
                .linkedLibrary("iconv"),
                // reqwest/hyper-util read system proxy settings on Apple.
                .linkedFramework("SystemConfiguration"),
                .linkedFramework("CoreFoundation"),
                // wgpu's Metal backend (GPU inference) — CAMetalLayer &co.
                .linkedFramework("Metal"),
                .linkedFramework("QuartzCore"),
            ]
        ),
    ]
)
