// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(sapient_ffiFFI)
import sapient_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_sapient_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_sapient_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureSapientFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * A loaded chat model plus its conversation state. Thread-safe; generation
 * calls on the same session serialize on the engine's internal lock.
 */
public protocol LlmSessionProtocol: AnyObject, Sendable {
    
    /**
     * Human-readable resolved backend (e.g. `CPU`, `Metal GPU`).
     */
    func backendLabel()  -> String
    
    /**
     * One blocking chat turn: appends the user message, generates the full
     * reply, commits both to the session history.
     */
    func chat(userMessage: String) throws  -> String
    
    /**
     * Async version of [`Self::chat`].
     */
    func chatAsync(userMessage: String) async throws  -> String
    
    /**
     * Stateless streamed turn over a full message array: the CALLER owns
     * the conversation (exactly `sapient serve`'s contract — the TS SDK's
     * `NativeTransport` is built on this), and the session history is
     * neither read nor written. Re-sent history stays cheap: the prefix
     * cache reuses the KV for the shared token prefix, so only the new
     * turn is prefilled. Cancel/error semantics match `chat_stream`.
     */
    func chatMessagesStream(messages: [Message], listener: TokenListener) async throws  -> String
    
    /**
     * Streaming chat turn: `listener.on_token` receives each text fragment
     * as it decodes; returning `false` cancels generation. Returns the full
     * (possibly cancelled-partial) reply, which is committed to history —
     * on cancel that is intentional, so the history matches what the user
     * saw and the prefix cache stays aligned with the engine's KV state.
     *
     * Error semantics: `Err` covers failures *starting* the stream (prompt
     * formatting, runtime). A generation failure *mid-stream* follows the
     * engine's in-band convention — the pipeline emits a final
     * `Error: …` text fragment and ends the stream (exactly what
     * `sapient serve` SSE clients see) — because the token channel carries
     * only `String`, with no sideband to distinguish error-close from
     * normal close. Promoting that to a typed error needs a
     * `Result`-carrying stream in `sapient-generate` (shared with
     * serve/CLI) and is tracked as a Phase 11 follow-up rung.
     */
    func chatStream(userMessage: String, listener: TokenListener) throws  -> String
    
    /**
     * Async version of [`Self::chat_stream`] — `on_token` fires from an
     * engine worker thread (never the caller's), so a JS host stays live to
     * receive tokens while the turn runs. Same cancel/error semantics.
     */
    func chatStreamAsync(userMessage: String, listener: TokenListener) async throws  -> String
    
    /**
     * Whether the weights are memory-mapped (RSS ≈ working set, not file size).
     */
    func isMmap()  -> Bool
    
    /**
     * The model alias this session was created with.
     */
    func model()  -> String
    
    /**
     * Clear the conversation (keeps the model loaded). The system prompt
     * given at load time is re-seeded.
     */
    func reset() 
    
    /**
     * The conversation so far (excluding any in-flight turn).
     */
    func transcript()  -> [Message]
    
}
/**
 * A loaded chat model plus its conversation state. Thread-safe; generation
 * calls on the same session serialize on the engine's internal lock.
 */
open class LlmSession: LlmSessionProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_sapient_ffi_fn_clone_llmsession(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_sapient_ffi_fn_free_llmsession(pointer, $0) }
    }

    
    /**
     * Download (if needed) and load a model from the curated catalog, then
     * hold it resident. Blocking — first call downloads weights; run this on
     * a background thread and surface progress in the host UI.
     */
public static func load(model: String, options: GenerationOptions)throws  -> LlmSession  {
    return try  FfiConverterTypeLlmSession_lift(try rustCallWithError(FfiConverterTypeSapientError_lift) {
    uniffi_sapient_ffi_fn_constructor_llmsession_load(
        FfiConverterString.lower(model),
        FfiConverterTypeGenerationOptions_lower(options),$0
    )
})
}
    

    
    /**
     * Human-readable resolved backend (e.g. `CPU`, `Metal GPU`).
     */
open func backendLabel() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_sapient_ffi_fn_method_llmsession_backend_label(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * One blocking chat turn: appends the user message, generates the full
     * reply, commits both to the session history.
     */
open func chat(userMessage: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeSapientError_lift) {
    uniffi_sapient_ffi_fn_method_llmsession_chat(self.uniffiClonePointer(),
        FfiConverterString.lower(userMessage),$0
    )
})
}
    
    /**
     * Async version of [`Self::chat`].
     */
open func chatAsync(userMessage: String)async throws  -> String  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_sapient_ffi_fn_method_llmsession_chat_async(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(userMessage)
                )
            },
            pollFunc: ffi_sapient_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_sapient_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_sapient_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterString.lift,
            errorHandler: FfiConverterTypeSapientError_lift
        )
}
    
    /**
     * Stateless streamed turn over a full message array: the CALLER owns
     * the conversation (exactly `sapient serve`'s contract — the TS SDK's
     * `NativeTransport` is built on this), and the session history is
     * neither read nor written. Re-sent history stays cheap: the prefix
     * cache reuses the KV for the shared token prefix, so only the new
     * turn is prefilled. Cancel/error semantics match `chat_stream`.
     */
open func chatMessagesStream(messages: [Message], listener: TokenListener)async throws  -> String  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_sapient_ffi_fn_method_llmsession_chat_messages_stream(
                    self.uniffiClonePointer(),
                    FfiConverterSequenceTypeMessage.lower(messages),FfiConverterTypeTokenListener_lower(listener)
                )
            },
            pollFunc: ffi_sapient_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_sapient_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_sapient_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterString.lift,
            errorHandler: FfiConverterTypeSapientError_lift
        )
}
    
    /**
     * Streaming chat turn: `listener.on_token` receives each text fragment
     * as it decodes; returning `false` cancels generation. Returns the full
     * (possibly cancelled-partial) reply, which is committed to history —
     * on cancel that is intentional, so the history matches what the user
     * saw and the prefix cache stays aligned with the engine's KV state.
     *
     * Error semantics: `Err` covers failures *starting* the stream (prompt
     * formatting, runtime). A generation failure *mid-stream* follows the
     * engine's in-band convention — the pipeline emits a final
     * `Error: …` text fragment and ends the stream (exactly what
     * `sapient serve` SSE clients see) — because the token channel carries
     * only `String`, with no sideband to distinguish error-close from
     * normal close. Promoting that to a typed error needs a
     * `Result`-carrying stream in `sapient-generate` (shared with
     * serve/CLI) and is tracked as a Phase 11 follow-up rung.
     */
open func chatStream(userMessage: String, listener: TokenListener)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeSapientError_lift) {
    uniffi_sapient_ffi_fn_method_llmsession_chat_stream(self.uniffiClonePointer(),
        FfiConverterString.lower(userMessage),
        FfiConverterTypeTokenListener_lower(listener),$0
    )
})
}
    
    /**
     * Async version of [`Self::chat_stream`] — `on_token` fires from an
     * engine worker thread (never the caller's), so a JS host stays live to
     * receive tokens while the turn runs. Same cancel/error semantics.
     */
open func chatStreamAsync(userMessage: String, listener: TokenListener)async throws  -> String  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_sapient_ffi_fn_method_llmsession_chat_stream_async(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(userMessage),FfiConverterTypeTokenListener_lower(listener)
                )
            },
            pollFunc: ffi_sapient_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_sapient_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_sapient_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterString.lift,
            errorHandler: FfiConverterTypeSapientError_lift
        )
}
    
    /**
     * Whether the weights are memory-mapped (RSS ≈ working set, not file size).
     */
open func isMmap() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_sapient_ffi_fn_method_llmsession_is_mmap(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * The model alias this session was created with.
     */
open func model() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_sapient_ffi_fn_method_llmsession_model(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Clear the conversation (keeps the model loaded). The system prompt
     * given at load time is re-seeded.
     */
open func reset()  {try! rustCall() {
    uniffi_sapient_ffi_fn_method_llmsession_reset(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * The conversation so far (excluding any in-flight turn).
     */
open func transcript() -> [Message]  {
    return try!  FfiConverterSequenceTypeMessage.lift(try! rustCall() {
    uniffi_sapient_ffi_fn_method_llmsession_transcript(self.uniffiClonePointer(),$0
    )
})
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLlmSession: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = LlmSession

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> LlmSession {
        return LlmSession(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: LlmSession) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LlmSession {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: LlmSession, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLlmSession_lift(_ pointer: UnsafeMutableRawPointer) throws -> LlmSession {
    return try FfiConverterTypeLlmSession.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLlmSession_lower(_ value: LlmSession) -> UnsafeMutableRawPointer {
    return FfiConverterTypeLlmSession.lower(value)
}






/**
 * Foreign-implemented token sink for streaming replies. Return `true` to
 * keep generating, `false` to cancel — cancellation drops the internal
 * receiver, which halts the engine at its next token emit.
 */
public protocol TokenListener: AnyObject, Sendable {
    
    func onToken(token: String)  -> Bool
    
}
/**
 * Foreign-implemented token sink for streaming replies. Return `true` to
 * keep generating, `false` to cancel — cancellation drops the internal
 * receiver, which halts the engine at its next token emit.
 */
open class TokenListenerImpl: TokenListener, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_sapient_ffi_fn_clone_tokenlistener(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_sapient_ffi_fn_free_tokenlistener(pointer, $0) }
    }

    

    
open func onToken(token: String) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_sapient_ffi_fn_method_tokenlistener_on_token(self.uniffiClonePointer(),
        FfiConverterString.lower(token),$0
    )
})
}
    

}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceTokenListener {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceTokenListener] = [UniffiVTableCallbackInterfaceTokenListener(
        onToken: { (
            uniffiHandle: UInt64,
            token: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<Int8>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> Bool in
                guard let uniffiObj = try? FfiConverterTypeTokenListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onToken(
                     token: try FfiConverterString.lift(token)
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterBool.lower($0) }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterTypeTokenListener.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface TokenListener: handle missing in uniffiFree")
            }
        }
    )]
}

private func uniffiCallbackInitTokenListener() {
    uniffi_sapient_ffi_fn_init_callback_vtable_tokenlistener(UniffiCallbackInterfaceTokenListener.vtable)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTokenListener: FfiConverter {
    fileprivate static let handleMap = UniffiHandleMap<TokenListener>()

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = TokenListener

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> TokenListener {
        return TokenListenerImpl(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: TokenListener) -> UnsafeMutableRawPointer {
        guard let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: handleMap.insert(obj: value))) else {
            fatalError("Cast to UnsafeMutableRawPointer failed")
        }
        return ptr
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TokenListener {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: TokenListener, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTokenListener_lift(_ pointer: UnsafeMutableRawPointer) throws -> TokenListener {
    return try FfiConverterTypeTokenListener.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTokenListener_lower(_ value: TokenListener) -> UnsafeMutableRawPointer {
    return FfiConverterTypeTokenListener.lower(value)
}




/**
 * Options for creating an [`LlmSession`]. All fields have defaults, so
 * foreign callers can construct this with only the fields they care about.
 */
public struct GenerationOptions {
    /**
     * Hard cap on new tokens per reply.
     */
    public var maxTokens: UInt32
    /**
     * Sampling temperature. Leaving every sampling field unset selects
     * greedy (deterministic) decoding.
     */
    public var temperature: Float?
    /**
     * Nucleus sampling threshold (0–1).
     */
    public var topP: Float?
    /**
     * Top-k cutoff. `0`/unset disables the filter.
     */
    public var topK: UInt32?
    /**
     * Repetition penalty (1.0 = off).
     */
    public var repetitionPenalty: Float?
    /**
     * Optional system prompt seeded at the start of the conversation.
     */
    public var systemPrompt: String?
    /**
     * Backend override: `auto` (default), `cpu`, `metal`, `wgpu`. Mobile
     * static libs are CPU-only today, so `auto` resolves to CPU there.
     */
    public var backend: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Hard cap on new tokens per reply.
         */maxTokens: UInt32 = UInt32(512), 
        /**
         * Sampling temperature. Leaving every sampling field unset selects
         * greedy (deterministic) decoding.
         */temperature: Float? = nil, 
        /**
         * Nucleus sampling threshold (0–1).
         */topP: Float? = nil, 
        /**
         * Top-k cutoff. `0`/unset disables the filter.
         */topK: UInt32? = nil, 
        /**
         * Repetition penalty (1.0 = off).
         */repetitionPenalty: Float? = nil, 
        /**
         * Optional system prompt seeded at the start of the conversation.
         */systemPrompt: String? = nil, 
        /**
         * Backend override: `auto` (default), `cpu`, `metal`, `wgpu`. Mobile
         * static libs are CPU-only today, so `auto` resolves to CPU there.
         */backend: String? = nil) {
        self.maxTokens = maxTokens
        self.temperature = temperature
        self.topP = topP
        self.topK = topK
        self.repetitionPenalty = repetitionPenalty
        self.systemPrompt = systemPrompt
        self.backend = backend
    }
}

#if compiler(>=6)
extension GenerationOptions: Sendable {}
#endif


extension GenerationOptions: Equatable, Hashable {
    public static func ==(lhs: GenerationOptions, rhs: GenerationOptions) -> Bool {
        if lhs.maxTokens != rhs.maxTokens {
            return false
        }
        if lhs.temperature != rhs.temperature {
            return false
        }
        if lhs.topP != rhs.topP {
            return false
        }
        if lhs.topK != rhs.topK {
            return false
        }
        if lhs.repetitionPenalty != rhs.repetitionPenalty {
            return false
        }
        if lhs.systemPrompt != rhs.systemPrompt {
            return false
        }
        if lhs.backend != rhs.backend {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(maxTokens)
        hasher.combine(temperature)
        hasher.combine(topP)
        hasher.combine(topK)
        hasher.combine(repetitionPenalty)
        hasher.combine(systemPrompt)
        hasher.combine(backend)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGenerationOptions: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GenerationOptions {
        return
            try GenerationOptions(
                maxTokens: FfiConverterUInt32.read(from: &buf), 
                temperature: FfiConverterOptionFloat.read(from: &buf), 
                topP: FfiConverterOptionFloat.read(from: &buf), 
                topK: FfiConverterOptionUInt32.read(from: &buf), 
                repetitionPenalty: FfiConverterOptionFloat.read(from: &buf), 
                systemPrompt: FfiConverterOptionString.read(from: &buf), 
                backend: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: GenerationOptions, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.maxTokens, into: &buf)
        FfiConverterOptionFloat.write(value.temperature, into: &buf)
        FfiConverterOptionFloat.write(value.topP, into: &buf)
        FfiConverterOptionUInt32.write(value.topK, into: &buf)
        FfiConverterOptionFloat.write(value.repetitionPenalty, into: &buf)
        FfiConverterOptionString.write(value.systemPrompt, into: &buf)
        FfiConverterOptionString.write(value.backend, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGenerationOptions_lift(_ buf: RustBuffer) throws -> GenerationOptions {
    return try FfiConverterTypeGenerationOptions.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGenerationOptions_lower(_ value: GenerationOptions) -> RustBuffer {
    return FfiConverterTypeGenerationOptions.lower(value)
}


/**
 * One message of the session transcript, for host-side display/persistence.
 */
public struct Message {
    /**
     * `system`, `user`, `assistant` or `tool`.
     */
    public var role: String
    public var content: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * `system`, `user`, `assistant` or `tool`.
         */role: String, content: String) {
        self.role = role
        self.content = content
    }
}

#if compiler(>=6)
extension Message: Sendable {}
#endif


extension Message: Equatable, Hashable {
    public static func ==(lhs: Message, rhs: Message) -> Bool {
        if lhs.role != rhs.role {
            return false
        }
        if lhs.content != rhs.content {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(role)
        hasher.combine(content)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMessage: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Message {
        return
            try Message(
                role: FfiConverterString.read(from: &buf), 
                content: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Message, into buf: inout [UInt8]) {
        FfiConverterString.write(value.role, into: &buf)
        FfiConverterString.write(value.content, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMessage_lift(_ buf: RustBuffer) throws -> Message {
    return try FfiConverterTypeMessage.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMessage_lower(_ value: Message) -> RustBuffer {
    return FfiConverterTypeMessage.lower(value)
}


/**
 * One row of the curated model catalog.
 */
public struct ModelEntry {
    /**
     * Canonical alias accepted by `LlmSession::load` (e.g. `qwen2.5-0.5b`).
     */
    public var alias: String
    /**
     * HuggingFace repository the alias resolves to.
     */
    public var repoId: String
    /**
     * Architecture family, for display.
     */
    public var family: String
    /**
     * Approximate parameter count, for display (e.g. `0.5B`).
     */
    public var params: String
    /**
     * Capability bucket: `chat`, `speech-to-text`, `text-to-speech`, `vision`.
     */
    public var category: String
    /**
     * Whether the repo is gated (needs an accepted license / HF token).
     */
    public var gated: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Canonical alias accepted by `LlmSession::load` (e.g. `qwen2.5-0.5b`).
         */alias: String, 
        /**
         * HuggingFace repository the alias resolves to.
         */repoId: String, 
        /**
         * Architecture family, for display.
         */family: String, 
        /**
         * Approximate parameter count, for display (e.g. `0.5B`).
         */params: String, 
        /**
         * Capability bucket: `chat`, `speech-to-text`, `text-to-speech`, `vision`.
         */category: String, 
        /**
         * Whether the repo is gated (needs an accepted license / HF token).
         */gated: Bool) {
        self.alias = alias
        self.repoId = repoId
        self.family = family
        self.params = params
        self.category = category
        self.gated = gated
    }
}

#if compiler(>=6)
extension ModelEntry: Sendable {}
#endif


extension ModelEntry: Equatable, Hashable {
    public static func ==(lhs: ModelEntry, rhs: ModelEntry) -> Bool {
        if lhs.alias != rhs.alias {
            return false
        }
        if lhs.repoId != rhs.repoId {
            return false
        }
        if lhs.family != rhs.family {
            return false
        }
        if lhs.params != rhs.params {
            return false
        }
        if lhs.category != rhs.category {
            return false
        }
        if lhs.gated != rhs.gated {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(alias)
        hasher.combine(repoId)
        hasher.combine(family)
        hasher.combine(params)
        hasher.combine(category)
        hasher.combine(gated)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeModelEntry: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ModelEntry {
        return
            try ModelEntry(
                alias: FfiConverterString.read(from: &buf), 
                repoId: FfiConverterString.read(from: &buf), 
                family: FfiConverterString.read(from: &buf), 
                params: FfiConverterString.read(from: &buf), 
                category: FfiConverterString.read(from: &buf), 
                gated: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: ModelEntry, into buf: inout [UInt8]) {
        FfiConverterString.write(value.alias, into: &buf)
        FfiConverterString.write(value.repoId, into: &buf)
        FfiConverterString.write(value.family, into: &buf)
        FfiConverterString.write(value.params, into: &buf)
        FfiConverterString.write(value.category, into: &buf)
        FfiConverterBool.write(value.gated, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeModelEntry_lift(_ buf: RustBuffer) throws -> ModelEntry {
    return try FfiConverterTypeModelEntry.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeModelEntry_lower(_ value: ModelEntry) -> RustBuffer {
    return FfiConverterTypeModelEntry.lower(value)
}


/**
 * Errors crossing the FFI boundary. The `reason` strings carry the
 * underlying `anyhow` chain so host apps can log something actionable.
 *
 * The field is deliberately NOT named `message`: UniFFI maps error enums to
 * Kotlin exception classes, and a `message` field collides with
 * `Throwable.message` ("hides member of supertype" — the generated Kotlin
 * doesn't compile; found by the Android sample app).
 */
public enum SapientError: Swift.Error {

    
    
    case Load(reason: String
    )
    case Generation(reason: String
    )
    case InvalidArgument(reason: String
    )
    case Internal(reason: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSapientError: FfiConverterRustBuffer {
    typealias SwiftType = SapientError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SapientError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Load(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 2: return .Generation(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 3: return .InvalidArgument(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 4: return .Internal(
            reason: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SapientError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Load(reason):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .Generation(reason):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .InvalidArgument(reason):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .Internal(reason):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(reason, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSapientError_lift(_ buf: RustBuffer) throws -> SapientError {
    return try FfiConverterTypeSapientError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSapientError_lower(_ value: SapientError) -> RustBuffer {
    return FfiConverterTypeSapientError.lower(value)
}


extension SapientError: Equatable, Hashable {}




extension SapientError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Host-OS thermal pressure. iOS `ProcessInfo.thermalState` maps 1:1;
 * Android `PowerManager` thermal status maps per Google's ADPF guidance:
 * NONE→NOMINAL, LIGHT→FAIR, MODERATE→SERIOUS, SEVERE and above→CRITICAL
 * ("SEVERE+ = drop below the sustainable level").
 */

public enum ThermalLevel {
    
    case nominal
    case fair
    case serious
    case critical
}


#if compiler(>=6)
extension ThermalLevel: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeThermalLevel: FfiConverterRustBuffer {
    typealias SwiftType = ThermalLevel

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ThermalLevel {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .nominal
        
        case 2: return .fair
        
        case 3: return .serious
        
        case 4: return .critical
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ThermalLevel, into buf: inout [UInt8]) {
        switch value {
        
        
        case .nominal:
            writeInt(&buf, Int32(1))
        
        
        case .fair:
            writeInt(&buf, Int32(2))
        
        
        case .serious:
            writeInt(&buf, Int32(3))
        
        
        case .critical:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeThermalLevel_lift(_ buf: RustBuffer) throws -> ThermalLevel {
    return try FfiConverterTypeThermalLevel.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeThermalLevel_lower(_ value: ThermalLevel) -> RustBuffer {
    return FfiConverterTypeThermalLevel.lower(value)
}


extension ThermalLevel: Equatable, Hashable {}






#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionFloat: FfiConverterRustBuffer {
    typealias SwiftType = Float?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterFloat.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterFloat.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMessage: FfiConverterRustBuffer {
    typealias SwiftType = [Message]

    public static func write(_ value: [Message], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMessage.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Message] {
        let len: Int32 = try readInt(&buf)
        var seq = [Message]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMessage.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeModelEntry: FfiConverterRustBuffer {
    typealias SwiftType = [ModelEntry]

    public static func write(_ value: [ModelEntry], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeModelEntry.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ModelEntry] {
        let len: Int32 = try readInt(&buf)
        var seq = [ModelEntry]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeModelEntry.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_MAYBE_READY: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureSapientFfiInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                uniffiFutureContinuationCallback,
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}
/**
 * The curated model catalog — every alias `LlmSession::load` accepts.
 */
public func listModels() -> [ModelEntry]  {
    return try!  FfiConverterSequenceTypeModelEntry.lift(try! rustCall() {
    uniffi_sapient_ffi_fn_func_list_models($0
    )
})
}
/**
 * Async version of [`LlmSession::load`] (a free function — uniffi
 * constructors are synchronous). Same semantics: downloads on first use,
 * holds the model resident, prefix cache on.
 */
public func loadSession(model: String, options: GenerationOptions)async throws  -> LlmSession  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_sapient_ffi_fn_func_load_session(FfiConverterString.lower(model),FfiConverterTypeGenerationOptions_lower(options)
                )
            },
            pollFunc: ffi_sapient_ffi_rust_future_poll_pointer,
            completeFunc: ffi_sapient_ffi_rust_future_complete_pointer,
            freeFunc: ffi_sapient_ffi_rust_future_free_pointer,
            liftFunc: FfiConverterTypeLlmSession_lift,
            errorHandler: FfiConverterTypeSapientError_lift
        )
}
/**
 * Resolve a model alias (with fuzzy matching) to its HuggingFace repo id.
 * Errors with the full catalog listing for unknown names.
 */
public func resolveAlias(name: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeSapientError_lift) {
    uniffi_sapient_ffi_fn_func_resolve_alias(
        FfiConverterString.lower(name),$0
    )
})
}
/**
 * Point the model cache (`HF_HOME`) somewhere sensible for the platform —
 * on mobile, the app's Caches directory, so the OS can reclaim downloads
 * and uninstall removes them (docs/MOBILE.md §5.4). Call BEFORE the first
 * session load. Swift/Kotlin hosts can equally `setenv("HF_HOME", …)`;
 * JS hosts (React Native) have no setenv, hence this export.
 */
public func setCacheDir(path: String)  {try! rustCall() {
    uniffi_sapient_ffi_fn_func_set_cache_dir(
        FfiConverterString.lower(path),$0
    )
}
}
/**
 * Feed the host OS's thermal state into the engine. The decode thread target
 * shrinks as pressure rises (fair → ¾ of cores, serious → ½, critical → ¼)
 * and restores when the device cools — same mechanism as the Linux sysfs
 * governor, fed by the platform's callback instead of a sensor file. Cheap
 * and thread-safe: call it directly from the OS notification/listener
 * (register at startup AND push the current state once — apps can already be
 * warm when launched). See `docs/MOBILE.md` §"Thermal" for the per-platform
 * wiring recipe.
 */
public func setThermalLevel(level: ThermalLevel)  {try! rustCall() {
    uniffi_sapient_ffi_fn_func_set_thermal_level(
        FfiConverterTypeThermalLevel_lower(level),$0
    )
}
}
/**
 * The thermal level most recently fed to [`set_thermal_level`]
 * (`Nominal` when never called). For app diagnostics/UI.
 */
public func thermalLevel() -> ThermalLevel  {
    return try!  FfiConverterTypeThermalLevel_lift(try! rustCall() {
    uniffi_sapient_ffi_fn_func_thermal_level($0
    )
})
}
/**
 * The SAPIENT engine version compiled into this library.
 */
public func version() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_sapient_ffi_fn_func_version($0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_sapient_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_sapient_ffi_checksum_func_list_models() != 56586) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sapient_ffi_checksum_func_load_session() != 27015) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sapient_ffi_checksum_func_resolve_alias() != 55233) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sapient_ffi_checksum_func_set_cache_dir() != 9493) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sapient_ffi_checksum_func_set_thermal_level() != 45426) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sapient_ffi_checksum_func_thermal_level() != 11661) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sapient_ffi_checksum_func_version() != 51660) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sapient_ffi_checksum_method_llmsession_backend_label() != 36281) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sapient_ffi_checksum_method_llmsession_chat() != 22486) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sapient_ffi_checksum_method_llmsession_chat_async() != 11059) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sapient_ffi_checksum_method_llmsession_chat_messages_stream() != 28273) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sapient_ffi_checksum_method_llmsession_chat_stream() != 14884) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sapient_ffi_checksum_method_llmsession_chat_stream_async() != 44262) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sapient_ffi_checksum_method_llmsession_is_mmap() != 61573) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sapient_ffi_checksum_method_llmsession_model() != 40496) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sapient_ffi_checksum_method_llmsession_reset() != 10704) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sapient_ffi_checksum_method_llmsession_transcript() != 26497) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sapient_ffi_checksum_method_tokenlistener_on_token() != 54686) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sapient_ffi_checksum_constructor_llmsession_load() != 58273) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitTokenListener()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureSapientFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all